### ISSUE TITLE
does not work with Fx 31 and Nightly (crashes on startup?)

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/blushproof#112]
When installing on Fx 31.0 linux64 from https://addons.mozilla.org/ru/firefox/addon/blushproof/?src=search, this appears in the terminal (and the extension does not work, at least when going to stevepavlina.com):

```
console.error: blushproof: 
  DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 113, in startup/<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 149, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 647, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 299, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 262, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://blushproof-at-mozilla-dot-org/blushproof/lib/main.js", line 8, in null
    let bpContentPolicy = require("bpContentPolicy");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 621, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 299, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 262, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpContentPolicy.js", line 11, in null
    let bpUI = require("bpUI");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 621, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 299, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 262, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpUI.js", line 11, in null
    const widget = require("sdk/widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 621, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 299, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 262, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    "The widget module is deprecated.  " +
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);
console.error: blushproof: 
Object
    - message = Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIIndexedDatabaseManager.initWindowless]
    - fileName = undefined
    - lineNumber = 93
    - stack = @undefined:93:NaN|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/monitor.js:4:7|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpUI.js:19:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpContentPolicy.js:11:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/main.js:8:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|run@resource://gre/modules/commonjs/sdk/addon/runner.js:149:9|startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:113:7|Handler.prototype.process@resource://gre/modules/Promise-backend.js:863:11|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:742:7|
    - toString = function () /* use strict */ toString
console.error: blushproof: 
Object
    - message = Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIIndexedDatabaseManager.initWindowless]
    - fileName = undefined
    - lineNumber = 93
    - stack = @undefined:93:NaN|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/monitor.js:4:7|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpUI.js:19:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/bpContentPolicy.js:11:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://blushproof-at-mozilla-dot-org/blushproof/lib/main.js:8:5|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|run@resource://gre/modules/commonjs/sdk/addon/runner.js:149:9|startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:113:7|Handler.prototype.process@resource://gre/modules/Promise-backend.js:863:11|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:742:7|
    - toString = function () /* use strict */ toString
```

**Comment by gregglind** [comment]
I am not sure how supported Blushproof is at the moment.  It was build around Fx17 era, and the addon-sdk has moved quite a bit since then.  

In particular, all the UI widgets have changed (for the better).  These will be a bit expensive to repair, so deciding on the right parts to prioritize is important!

Do you need the whole addon, or just some part of it (say, the library for the blushlist)?

**Comment by aleksejrs** [comment]
I only wanted to see it, and test its compatibility with e10s (it was in a list, see the automatic reference above).
